[tool.poetry]
name = "routeplan"
version = "0.1.0"
description = ""
authors = ["chuan.chen"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
networkx = "^3.3"
matplotlib = "^3.9.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
